### ISSUE TITLE
Restrict access to `/metrics` from the public network

### ISSUE THREAD

**Issue by ochaplashkin** [tarantool/docbot#43]
[TNT-992](https://jira.vk.team/browse/TNT-992)

**Comment by ochaplashkin** [comment]
- [ ] Set generated `prometheus token` to the Dokku environment variables
- [ ] Deploy `docbot` service
- [ ] Change the prometheus config in the `scrape_config` section and add `bearer_token`
```yaml
- job_name: 'test'
    metrics_path: '/metrics'
    scheme: "http"
    bearer_token: <token_here>
    ...
```
- [ ] Check Grafana `docbot` dashboard
- [ ] Check that there's no way to access the metrics without Bearer token
